### ISSUE TITLE
Symfony 4 translatable retrieving data

### ISSUE THREAD

**Issue by pietrach** [KnpLabs/DoctrineBehaviors#416] opened 2019-03-24 19:37 UTC
I'm trying to retrieve translation data:

```php
  $cats = $this->getDoctrine()
            ->getRepository(Category::class)
            ->findAll();
         foreach($cats as $cat){
             var_dump($cat->translate('en')->getText());
         }
```
Results:
```
D:\wamp\www\symfony\src\Controller\Admin\CategoryController.php:29:null
D:\wamp\www\symfony\src\Controller\Admin\CategoryController.php:29:null
D:\wamp\www\symfony\src\Controller\Admin\CategoryController.php:29:null
D:\wamp\www\symfony\src\Controller\Admin\CategoryController.php:29:null
```

Below entity classes:

```php
namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;

/**
 * Category
 *
 * @ORM\Table(name="categories", indexes={@ORM\Index(name="admin_added_id", columns={"admin_added_id"}), @ORM\Index(name="parent_id", columns={"parent_id"}), @ORM\Index(name="admin_updated_id", columns={"admin_updated_id"})})
 * @ORM\Entity(repositoryClass="App\Repository\CategoryRepository")
 */
class Category {

    use ORMBehaviors\Translatable\Translatable;

    private $order = '0';

    /**
     * @var bool
     *
     * @ORM\Column(name="status", type="boolean", nullable=false)
     */
    private $status = '0';

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="created_at", type="datetime", nullable=true)
     */
    private $createdAt;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="updated_at", type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\OneToMany(targetEntity="App\Entity\Category", mappedBy="parent")
     */
    private $children;

    /**
     * @var \App\Entity\Category
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Category")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="parent_id", referencedColumnName="id")
     * })
     */
    private $parent;

    /**
     * @var \App\Entity\Admin
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Admin")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="admin_added_id", referencedColumnName="id")
     * })
     */
    private $adminAdded;

    /**
     * @var \App\Entity\Admin
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Admin")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="admin_updated_id", referencedColumnName="id")
     * })
     */
    private $adminUpdated;

    public function __call($method, $args) {
        if (!method_exists(self::getTranslationEntityClass(), $method)) {
            $method = 'get' . ucfirst($method);
        }

        return $this->proxyCurrentLocaleTranslation($method, $args);
    }

    /**
     * Constructor
     */
    public function __construct() {
        $this->children = new ArrayCollection();
    }

    public function getOrder(): ?int {
        return $this->order;
    }

    public function setOrder(int $order): self {
        $this->order = $order;

        return $this;
    }

    public function getStatus(): ?bool {
        return $this->status;
    }

    public function setStatus(bool $status): self {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeInterface $createdAt): self {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getId(): ?int {
        return $this->id;
    }

    /**
     * @return Collection|Category[]
     */
    public function getChildren(): Collection {
        return $this->children;
    }

    public function addChild(Category $child): self {
        if (!$this->children->contains($child)) {
            $this->children[] = $child;
            $child->setParent($this);
        }

        return $this;
    }

    public function removeChild(Category $child): self {
        if ($this->children->contains($child)) {
            $this->children->removeElement($child);
            // set the owning side to null (unless already changed)
            if ($child->getParent() === $this) {
                $child->setParent(null);
            }
        }

        return $this;
    }

    public function getParent(): ?self {
        return $this->parent;
    }

    public function setParent(?self $parent): self {
        $this->parent = $parent;

        return $this;
    }

    public function getAdminAdded(): ?Admin {
        return $this->adminAdded;
    }

    public function setAdminAdded(?Admin $adminAdded): self {
        $this->adminAdded = $adminAdded;

        return $this;
    }

    public function getAdminUpdated(): ?Admin {
        return $this->adminUpdated;
    }

    public function setAdminUpdated(?Admin $adminUpdated): self {
        $this->adminUpdated = $adminUpdated;

        return $this;
    }
}

```
```php
namespace App\Entity;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;

use Doctrine\ORM\Mapping as ORM;

/**
 * CategoryTranslation
 *
 * @ORM\Table(name="categories_translations", uniqueConstraints={@ORM\UniqueConstraint(name="category_id", columns={"translatable_id", "locale"})}, indexes={@ORM\Index(name="IDX_78B2B09112469DE2", columns={"translatable_id"})})
 * @ORM\Entity
 */
class CategoryTranslation {

    use ORMBehaviors\Translatable\Translation;

    /**
     * @var string|null
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @var string|null
     *
     * @ORM\Column(name="title_metatag", type="string", length=255, nullable=true)
     */
    private $titleMetatag;

    /**
     * @var string|null
     *
     * @ORM\Column(name="description_metatag", type="string", length=255, nullable=true)
     */
    private $descriptionMetatag;

    /**
     * @var string|null
     *
     * @ORM\Column(name="keywords_metatag", type="string", length=255, nullable=true)
     */
    private $keywordsMetatag;

    /**
     * @var string|null
     *
     * @ORM\Column(name="slug", type="string", length=255, nullable=true)
     */
    private $slug;

    /**
     * @var string|null
     *
     * @ORM\Column(name="text", type="text", length=65535, nullable=true)
     */
    private $text;

    public function getName(): ?string {
        return $this->name;
    }

    public function setName(?string $name): self {
        $this->name = $name;

        return $this;
    }

    public function getTitleMetatag(): ?string {
        return $this->titleMetatag;
    }

    public function setTitleMetatag(?string $titleMetatag): self {
        $this->titleMetatag = $titleMetatag;

        return $this;
    }

    public function getDescriptionMetatag(): ?string {
        return $this->descriptionMetatag;
    }

    public function setDescriptionMetatag(?string $descriptionMetatag): self {
        $this->descriptionMetatag = $descriptionMetatag;

        return $this;
    }

    public function getKeywordsMetatag(): ?string {
        return $this->keywordsMetatag;
    }

    public function setKeywordsMetatag(?string $keywordsMetatag): self {
        $this->keywordsMetatag = $keywordsMetatag;

        return $this;
    }

    public function getSlug(): ?string {
        return $this->slug;
    }

    public function setSlug(?string $slug): self {
        $this->slug = $slug;

        return $this;
    }

    public function getText(): ?string {
        return $this->text;
    }

    public function setText(?string $text): self {
        $this->text = $text;

        return $this;
    }

}
```

**Comment by gponty** [comment] 2019-10-11 21:04
Same issue here, currentLocale is always null :

$this = {App\Entity\Referentiel\CodifTranslation} [4]
 libelleCodif = null
 id = null
 locale = "fr"
 translatable = {App\Entity\Referentiel\Codif} [11]
  id = {int} 20
  codeCodif = "ETOILE"
  etatCodif = {int} 5
  userAjout = {Proxies\__CG__\App\Entity\User} [28]
  userModif = {Proxies\__CG__\App\Entity\User} [28]
  translations = {Doctrine\Common\Collections\ArrayCollection} [1]
  newTranslations = {Doctrine\Common\Collections\ArrayCollection} [1]
  currentLocale = null
  defaultLocale = "en"
  createdAt = {DateTime} [3]
  updatedAt = {DateTime} [3]

**Comment by TomasVotruba** [comment] 2020-01-01 17:39
Please send failing test case to current version, so we can verify the issue is still there. Closing for now

**Closed by TomasVotruba** 2020-01-01 17:39 UTC
