### ISSUE TITLE
[Softdeleteable] Problem with deleting proxy

### ISSUE THREAD

**Issue by martinknor** [KnpLabs/DoctrineBehaviors#397] opened 2018-08-06 10:00 UTC
Hi,

i have a problem with deleting proxy of entity. The problem is, when subscriber call `$old->getDeletedAt()` from here: https://github.com/KnpLabs/DoctrineBehaviors/blob/master/src/ORM/SoftDeletable/SoftDeletableSubscriber.php#L54, uow set entity back to MANAGED state (proxy is loaded) and it leads to fail, because next `persist` method doesn't remove this entity from `scheduleForDelete` queue.
This can be possibly dangerous, because it delete entity from db.

My resolution is to add preRemove event to subscriber, which loads the proxy.

```php
public function preRemove(LifecycleEventArgs $args)
	{

		$em = $args->getEntityManager();
		$entity = $args->getEntity();
		$classMetadata = $em->getClassMetadata(get_class($entity));

		if ($this->isSoftDeletable($classMetadata) && $entity instanceof Proxy && !$entity->__isInitialized__) {
			$entity->__load();
		}
	}


 public function getSubscribedEvents()
    {
        return [Events::onFlush, Events::loadClassMetadata, Events::preRemove];
    }
```

**Comment by TomasVotruba** [comment] 2019-12-18 20:23
Hi, we need failing test case to be added to verify the issue.
Then a fix you suggest, to prove it's been removed.

Feel free to send PR if you need.

I'm gonna close this now since the issue is more than a year old the has been changed a lot.

**Closed by TomasVotruba** 2019-12-18 20:23 UTC

**Comment by Pechynho** [comment] 2020-09-14 14:42
This is still an issue. I had to use martinknor's solution to bypass this problem.
