### ISSUE TITLE
Trouble with make:entity

### ISSUE THREAD

**Issue by laurentHCM** [KnpLabs/DoctrineBehaviors#481] opened 2020-01-02 02:51 UTC
Hi Tomas,

I think there is just a small side-effect with the new release.
Each time I want to create an entity with bin/console make:entity , I have to following error message.
But if the entity is created, even empty, if I use again bin/console make:entity to provide fields to the entity , there is no more error message.
So the workaround is easy to manage.
Thanks.

php bin/console make:entity
Class name of the entity to create or update (e.g. BraveKangaroo):
 > BraveKangaroo

 created: src/Entity/BraveKangaroo.php
 created: src/Repository/BraveKangarooRepository.php

In BlameableSubscriber.php line 57:

  Call to a member function getName() on null

make:entity [-a|--api-resource] [--regenerate] [--overwrite] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<name>]

**Comment by TomasVotruba** [comment] 2020-01-02 10:17
Hi,

what change in the subscriber you think would fix that?

**Comment by laurentHCM** [comment] 2020-01-02 13:34
Hi Tomas,

I will try to find and be back soon.

De : Tomas Votruba [mailto:notifications@github.com]
Envoyé : jeudi 2 janvier 2020 17:17
À : KnpLabs/DoctrineBehaviors
Cc : laurent BARBEAU; Author
Objet : Re: [KnpLabs/DoctrineBehaviors] Trouble with make:entity (#481)


Hi,

what change in the subscriber you think would fix that?

**Comment by laurentHCM** [comment] 2020-01-03 06:41
Hi Tomas,

Maybe in all subscribers we have to had a test to check if reflClass is not null , like below for BlameableSubscriber .
if (null == $classMetadata->reflClass || ! is_a($classMetadata->reflClass->getName(), BlameableInterface::class, true)) {

Do you think it’s enough ?

De : Tomas Votruba [mailto:notifications@github.com]
Envoyé : jeudi 2 janvier 2020 17:17
À : KnpLabs/DoctrineBehaviors
Cc : laurent BARBEAU; Author
Objet : Re: [KnpLabs/DoctrineBehaviors] Trouble with make:entity (#481)


Hi,

what change in the subscriber you think would fix that?

**Comment by TomasVotruba** [comment] 2020-01-03 10:18
Hi, 

that might be a fix. I still wonder why it's null and not the class name.
Could you think of any difference to your other entities?

**Comment by laurentHCM** [comment] 2020-01-03 10:24
Hi,

I don’t think it’s related to my other entities.
I think that probably the event is triggered too early because it occurs as soon as I provided the entity name.
And then the second time I launch the make:entity and provide the same name , as the entity is already created (even totally empty) , I can add the description of  the properties.
Do you want me to try to search a better explanation and maybe a better fix ?

De : Tomas Votruba [mailto:notifications@github.com]
Envoyé : vendredi 3 janvier 2020 17:19
À : KnpLabs/DoctrineBehaviors
Cc : laurent BARBEAU; Author
Objet : Re: [KnpLabs/DoctrineBehaviors] Trouble with make:entity (#481)


Hi,

that might be a fix. I still wonder why it's null and not the class name.
Could you think of any difference to your other entities?

**Comment by TomasVotruba** [comment] 2020-01-03 10:53
> I think that probably the event is triggered too early because it occurs as soon as I provided the entity name.

I see. In that case, please send PR with checking the class name.
Also a  descriptive comment with this case would be helpful for furute generations.

**Comment by ewbarnard** [comment] 2020-01-19 00:16
I see the same issue, and the analysis appears correct to me. I see "Call to a member function getName() on null" immediately after "console make:entity" creates the new entity class and new repository class. I'm seeing this is Symfony 5. 

I think checking for null is reasonable. There might be some OTHER issue that would get masked, but during make:entity we don't really need timestampable behavior. Not during the code generation step.

**Comment by TomasVotruba** [comment] 2020-01-19 00:22
We agreed on it. Test case for this use case is needed to verify the fix

**Comment by ewbarnard** [comment] 2020-01-19 00:53
I'll see if I can figure out a test case. I can certainly reproduce the problem and this will be an excuse to dig into the maker bundle.

**Comment by ewbarnard** [comment] 2020-01-19 14:05
Confirmed - my PR does fix the problem that brought me here originally. I pointed composer to my fork of this repository, updated, and was able to complete the SymfonyCasts chapter using Symfony 5.

**Comment by laurentHCM** [comment] 2020-01-20 00:30
Hi Tomas,

While seeing the last message posted by Edward, I just understand what you wanted me to do.
I apologize for not doing but I was not aware of the way to proceed in a project.
I will be better in the future.
Thanks again for your job with those bundles.

Laurent


De : Laurent BARBEAU
Envoyé : vendredi 3 janvier 2020 17:24
À : KnpLabs/DoctrineBehaviors
Objet : RE: [KnpLabs/DoctrineBehaviors] Trouble with make:entity (#481)

Hi,

I don’t think it’s related to my other entities.
I think that probably the event is triggered too early because it occurs as soon as I provided the entity name.
And then the second time I launch the make:entity and provide the same name , as the entity is already created (even totally empty) , I can add the description of  the properties.
Do you want me to try to search a better explanation and maybe a better fix ?

De : Tomas Votruba [mailto:notifications@github.com]
Envoyé : vendredi 3 janvier 2020 17:19
À : KnpLabs/DoctrineBehaviors
Cc : laurent BARBEAU; Author
Objet : Re: [KnpLabs/DoctrineBehaviors] Trouble with make:entity (#481)


Hi,

that might be a fix. I still wonder why it's null and not the class name.
Could you think of any difference to your other entities?

**Comment by ewbarnard** [comment] 2020-01-20 00:46
@laurentHCM Hi Laurent - I'm very glad you reported the problem, since it answered my question as well. Luckily I had time to dig in and discover how to test it. You were helpful!

Ed

**Comment by TomasVotruba** [comment] 2020-06-22 22:47
Closing for missing test, that we need to reproduce the issue.

**Closed by TomasVotruba** 2020-06-22 22:47 UTC
