### ISSUE TITLE
[Translatable] doTranslate() should return self

### ISSUE THREAD

**Issue by Jupi007** [KnpLabs/DoctrineBehaviors#641] opened 2021-07-26 19:30 UTC
Php intelephense give me some errors like this one, when I try to access to any setter of my translated entities:
```
Undefined method 'setTitle'.
```
This is due to `doTranslate()` and `translate()` method of `TranslatableMethodsTrait` which actually returns a `TranslationInterface` type and so don't have `setTitle` defined. <del>If those two methods was returning `self`, that could fix the problem.</del>
**Edit:** I don't think it is a good idea to return `self`, but I don't have any other alternative solution.

**Comment by TomasVotruba** [comment] 2021-08-09 09:49
Hi, thanks for reporting. I'm not sure what your goal is. Could you send PR with failing test or the feature you would like to see?

**Comment by Jupi007** [comment] 2021-08-09 10:02
Hi,
I'm really sorry to have sent this issue, because it is not a real problem as it doesn't throw Php error at all.

In fact, in the doc of the translatable behavior there is this code snippet:

```php
/** @var \Knp\DoctrineBehaviors\Contract\Entity\TranslatableInterface $category */
$category = new Category();
$category->translate('fr')->setName('Chaussures');
```
But as the `translate()` method returns `TranslatableMethodsTrait` type, the `setName()` method is not defined and Php intelephense give me some errors.
But it doesn't create real Php error at all, it just give me warning in my IDE console.

The "solution" (big word for nothing) I found is doing this:

```php
$category = new Category();
$category->translate('fr');
$category->setName('Chaussures');
```

Like this `setName()` is defined, and no intelephense warning shown.

So maybe should you update the documentation, what do you think?

**Comment by TomasVotruba** [comment] 2021-08-09 10:20
Thanks for update. So the issue is that if `TranslatableInterface` is returned, your custom methods are missing?

> So maybe should you update the documentation, what do you think?

Might be useful :+1: Could you send PR?

**Comment by Jupi007** [comment] 2021-08-09 10:23
> Might be useful +1 Could you send PR?

Ofc, will do this with pleasure :)

**Comment by TomasVotruba** [comment] 2021-08-09 10:25
> Edit: I don't think it is a good idea to return self, but I don't have any other alternative solution.

Btw, this might be useful solution for currently working code. What made you avoid this option?

**Comment by Jupi007** [comment] 2021-08-09 10:50
I had thought that return `self` was a bad idea because if `translate()` return `self` type, well `doTranslate()` should return it too and so, this phpdoc comment should be removed:

https://github.com/KnpLabs/DoctrineBehaviors/blob/c8d0112c44f6e6b23f9eda69af2f206dd3427d3b/src/Model/Translatable/TranslatableMethodsTrait.php#L156-L157

But is `self` refer to `Category` in the upper example (what I thought) or to the interface itself? 🤔

**Comment by TomasVotruba** [comment] 2021-08-09 10:53
I have no idea how translations works here, as I don't use them. So I can only believe your findings.

**Comment by Jupi007** [comment] 2021-08-09 11:05
IMO leave the translatable code as it, and update the documentation is the best solution.
I just played a bit with the code, and return `self` is causing annoying side effects.

**Comment by TomasVotruba** [comment] 2021-08-09 11:16
Let's try it then

**Comment by Jupi007** [comment] 2021-08-09 12:33
😔 I'm really sorry, but the way I proposed to modify the documentation isn't valid at all, because define a translation have to be do like this:

```php
$category->translate('fr')->setName('Chaussures');
```

And not like that:

```php
$category->translate('fr');
$category->setName('Chaussures');
```

Because `setName()` isn't defined on `Category` class itself, but on `CategoryTranslation` one (in fact it's me who added shortcut methods to `Category`).

---

I can propose to create a `TranslatableSetterTrait`:

```php
trait TranslatableSetterTrait
{
    protected function setTranslatedProperty(string $property, $value, string $locale = null): void
    {
        $this->translate($locale)->$property($value);
    }
}
```
And then use it like this:

```php
class Category implements TranslatableInterface
{
    use TranslatableTrait;
    use TranslatableSetterTrait;

    // ...

    public function setName(string $name, string $locale = null): self
    {
        $this->setTranslatedProperty('setName', $name, $locale);

        return $this;
    }
}
```

Like that `setName()` is defined inside `Category` class:

```php
$category->setName('Chaussures', 'fr');

// instead of:
$category->translate('fr')->setName('Chaussures'); // Undefined method 'setName'.
```

And so intelephense shut up and the final usage code is simpler in bonus :)

**Comment by TomasVotruba** [comment] 2021-08-09 13:20
Thanks for investigation and looking for the best approach :+1: 

I scanned quickly through it, and this will be missed by static analysis:

```bash
$this->translate($locale)->$property($value);
```

I believe generics `@implements` might be an answer here. As interface of specific type is returned: https://phpstan.org/blog/generics-in-php-using-phpdocs. At least for PHPStan

**Comment by Jupi007** [comment] 2021-08-09 13:47
> I believe generics `@implements` might be an answer here. As interface of specific type is returned: https://phpstan.org/blog/generics-in-php-using-phpdocs. At least for PHPStan

What do you mean (sorry I'm really not an expert of all this phpdoc stuffs)?

**Comment by TomasVotruba** [comment] 2021-08-09 13:58
See https://phpstan.org/blog/generics-in-php-using-phpdocs and "@implements" syntax

Also this might help https://tomasvotruba.com/blog/2021/01/04/phpstan-abstract-parent-generics-dummies

With that, you can say your entity implements specific interface (here the `TranslatableInterface`), but has also current type. Smarter "self" let's say :)

**Comment by Jupi007** [comment] 2021-08-09 14:31
Sorry, but I still don't understand how this could help 😞

To keep the category example, I have this situation (I'll try to resume the situation as simpler as possible):

- `Category` class which implement the `TranslatableInterface` and so have `translate()` method ;
- `CategoryTranslation` class which have `setName()` method ;
- when I call `translate()` from `Category` class, it return me a `CategoryTranslation` instance but typed with `TranslationInterface`, so it doesn't have `setName()` method defined. The code is executed well by PHP, but intelephense give me warnings.

Honestly, I don't see where to put `@implements` in this situation.
I'm really sorry to be boring like that 😞

**Comment by Kocal** [comment] 2021-08-09 15:20
I think Tomas means something like this:

```php
/**
 * @implements TranslatableInterface<CategoryInterface>
 */
class Category implements TranslatableInterface {

}

/**
 * @implements TranslationInterface<Category>
 */
class CategoryTranslation implemenst TranslationInterface {

}
```

This is what [our PHPStan extension](https://github.com/KnpLabs/DoctrineBehaviors#phpstan) does, but doing it manually could help PHP intelephense

**Comment by Jupi007** [comment] 2021-08-09 15:36
Hi @Kocal and thank you :)

Sadly, this doesn't work.
I added these comments to my entity, and I even installed and configured PHPStan but I still have errors like with both PHPStan and intelephense:

`Call to an undefined method Knp\DoctrineBehaviors\Contract\Entity\TranslationInterface::setName().`

**Comment by TomasVotruba** [comment] 2021-08-09 21:51
I see. In such case I think we can close this issue, as current PHP does not support it.

**Closed by TomasVotruba** 2021-08-09 21:51 UTC

**Comment by Jupi007** [comment] 2021-08-10 08:39
> I see. In such case I think we can close this issue, as current PHP does not support it.

Okay, thanks anyway for your help :)
